import React from 'react';
import { FileSpreadsheet, Download, FileText } from 'lucide-react';
import { ReviewPaper } from '../types';
import { exportToExcel, exportToCSV } from '../services/exportUtils';

interface ExportBarProps {
  papers: ReviewPaper[];
  topic: string;
}

export const ExportBar: React.FC<ExportBarProps> = ({ papers, topic }) => {
  if (papers.length === 0) return null;

  const exportMarkdown = () => {
    const mdLines = [
      `# Literature Review Matrix: ${topic}`,
      `Generated by LitBuddy on ${new Date().toLocaleDateString()}`,
      '',
      '| Score | Title | Year | Authors | Core Problem | Methodology | Key Findings | Gaps | DOI |',
      '| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |'
    ];

    papers.forEach(p => {
      const score = p.relevance_score || 4;
      const title = (p.title || '').replace(/\|/g, '\\|');
      const year = p.year || '';
      const authors = (p.authors || []).slice(0, 3).join(', ').replace(/\|/g, '\\|');
      const problem = (p.core_problem || '').replace(/\|/g, '\\|');
      const method = (p.methodology || '').replace(/\|/g, '\\|');
      const findings = (p.key_findings || '').replace(/\|/g, '\\|');
      const gaps = (p.research_gaps || '').replace(/\|/g, '\\|');
      const link = p.doi_link ? `[Link](${p.doi_link})` : '';

      mdLines.push(`| ${score}/5 | ${title} | ${year} | ${authors} | ${problem} | ${method} | ${findings} | ${gaps} | ${link} |`);
    });

    const blob = new Blob([mdLines.join('\n')], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `litbuddy_review_${topic.slice(0, 20).replace(/\s+/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="rounded-2xl dark:bg-[#1e1f20] bg-white border dark:border-[#3c4043] border-[#dadce0] px-5 py-3 mb-6 flex flex-col sm:flex-row items-center justify-between gap-3 shadow-md">
      <div className="text-xs dark:text-[#9aa0a6] text-[#5f6368]">
        Synthesized <strong className="font-semibold dark:text-[#e3e3e3] text-[#1f1f1f]">{papers.length}</strong> academic publications
      </div>

      <div className="flex items-center gap-2">
        <button
          onClick={() => exportToExcel(papers, topic)}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full dark:bg-[#282a2c] bg-slate-100 hover:dark:bg-[#3c4043] hover:bg-slate-200 dark:text-[#e3e3e3] text-[#1f1f1f] border dark:border-[#3c4043] border-slate-300 text-xs font-medium transition-colors"
        >
          <FileSpreadsheet className="w-3.5 h-3.5 text-[#81c995]" />
          <span>Excel (.xlsx)</span>
        </button>

        <button
          onClick={() => exportToCSV(papers, topic)}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full dark:bg-[#282a2c] bg-slate-100 hover:dark:bg-[#3c4043] hover:bg-slate-200 dark:text-[#e3e3e3] text-[#1f1f1f] border dark:border-[#3c4043] border-slate-300 text-xs font-medium transition-colors"
        >
          <Download className="w-3.5 h-3.5 text-[#8ab4f8]" />
          <span>CSV</span>
        </button>

        <button
          onClick={exportMarkdown}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full dark:bg-[#282a2c] bg-slate-100 hover:dark:bg-[#3c4043] hover:bg-slate-200 dark:text-[#e3e3e3] text-[#1f1f1f] border dark:border-[#3c4043] border-slate-300 text-xs font-medium transition-colors"
        >
          <FileText className="w-3.5 h-3.5 text-[#c58af9]" />
          <span>Markdown</span>
        </button>
      </div>
    </div>
  );
};
