import React from 'react';
import { X, Shield } from 'lucide-react';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
  type: 'terms' | 'privacy';
}

export const LegalModal: React.FC<LegalModalProps> = ({ isOpen, onClose, type }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-fadeIn">
      <div className="w-full max-w-2xl bg-[#1e1f20] border border-[#3c4043] rounded-3xl shadow-2xl p-6 sm:p-8 max-h-[85vh] flex flex-col text-xs text-[#c4c7c5]">
        <div className="flex items-center justify-between pb-4 border-b border-[#3c4043] mb-4">
          <div className="flex items-center gap-2">
            <Shield className="w-5 h-5 text-[#8ab4f8]" />
            <h3 className="text-base font-semibold text-[#e3e3e3]">
              {type === 'terms' ? 'Terms & Conditions' : 'Privacy & Security Policy'}
            </h3>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1 rounded-lg text-[#9aa0a6] hover:text-[#e3e3e3] hover:bg-[#282a2c] transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto space-y-4 pr-2 leading-relaxed text-[#9aa0a6]">
          {type === 'terms' ? (
            <>
              <p className="text-[#e3e3e3] font-medium">1. Purpose and Usage</p>
              <p>
                LitBuddy is an autonomous literature review engine designed for academic and scientific inquiry. It provides automated metadata indexing, Open Access PDF retrieval, and AI-assisted synthesis.
              </p>
              <p className="text-[#e3e3e3] font-medium">2. BYOK (Bring Your Own Key)</p>
              <p>
                Users provide their own API credentials (Groq, Google Gemini, OpenRouter, DeepSeek, NVIDIA NIM). Users retain full responsibility for complying with provider terms of service, quotas, and billing.
              </p>
              <p className="text-[#e3e3e3] font-medium">3. Intellectual Property & Citation</p>
              <p>
                All academic publications retrieved through OpenAlex, Crossref, arXiv, Europe PMC, and Semantic Scholar remain the intellectual property of their original authors and publishers. LitBuddy facilitates discovery under fair-use academic research guidelines.
              </p>
              <p className="text-[#e3e3e3] font-medium">4. Disclaimer of Warranty</p>
              <p>
                Syntheses generated by AI models are intended as research aids. Users are encouraged to inspect original publications via the provided DOI links prior to citing in definitive peer-reviewed publications.
              </p>
            </>
          ) : (
            <>
              <p className="text-[#e3e3e3] font-medium">1. Zero Telemetry & Data Selling</p>
              <p>
                LitBuddy does not sell, broker, or transmit user research topics, queries, or personal data to third-party data brokers or marketing platforms.
              </p>
              <p className="text-[#e3e3e3] font-medium">2. Local & Encrypted Key Storage</p>
              <p>
                Runtime API keys configured through the BYOK hub are encrypted using industry-standard AES-256 or retained strictly in ephemeral local session memory. Keys are transmitted only directly to the respective model provider during synthesis calls.
              </p>
              <p className="text-[#e3e3e3] font-medium">3. Caching & Efficiency Protocol</p>
              <p>
                To minimize API rate-limits and token consumption, LitBuddy caches discovered candidate paper pools (Tier 1) and paper syntheses (Tier 2) in local SQLite database storage.
              </p>
            </>
          )}
        </div>

        <div className="pt-4 mt-4 border-t border-[#3c4043] flex justify-end">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-[#8ab4f8] text-[#131314] font-semibold text-xs hover:bg-[#8ab4f8]/90 transition-colors"
          >
            I Understand
          </button>
        </div>
      </div>
    </div>
  );
};
