import React, { useState } from 'react';
import {
  FileText,
  Copy,
  Check,
  Download,
  Share2,
  Bot,
  ExternalLink,
  Sparkles,
  X
} from 'lucide-react';
import { ReviewPaper, RawPaperMetadata } from '../types';

interface ResearchContextExporterProps {
  isOpen: boolean;
  onClose: () => void;
  topic: string;
  synthesizedPapers: ReviewPaper[];
  candidatePool?: RawPaperMetadata[];
  recentQuestions?: string[];
}

export const ResearchContextExporter: React.FC<ResearchContextExporterProps> = ({
  isOpen,
  onClose,
  topic,
  synthesizedPapers,
  candidatePool = [],
  recentQuestions = []
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  // Format comprehensive context package
  const contextText = `# Grounded Research Context Package: ${topic || 'Academic Investigation'}
Generated by LitBuddy Research Operating System (Offline Vault)

## 1. Research Topic & Objectives
**Primary Topic:** ${topic || 'General SOTA Literature Survey'}
**User Inquiries & Focus Areas:**
${
  recentQuestions.length > 0
    ? recentQuestions.map((q) => `- ${q}`).join('\n')
    : '- Deep methodology comparative analysis and empirical benchmark extraction.'
}

## 2. Peer-Reviewed Grounded Papers (${synthesizedPapers.length} Verified Works)
${synthesizedPapers
  .map(
    (p, idx) => `### [${idx + 1}] ${p.title} (${p.year || 2024})
- **Authors:** ${Array.isArray(p.authors) ? p.authors.join(', ') : 'Research Group'}
- **DOI / Link:** ${(p as any).doi ? `https://doi.org/${(p as any).doi}` : p.doi_link || 'N/A'}
- **Core Problem:** ${p.core_problem || 'Not specified'}
- **Methodology:** ${p.methodology || 'Not specified'}
- **Key Findings:** ${p.key_findings || 'Not specified'}
- **Research Gaps Identified:** ${p.research_gaps || 'None flagged'}
`
  )
  .join('\n')}

## 3. Instructions for External AI (ChatGPT, Claude 3.5, Gemini 1.5 Pro)
You are an expert principal research scientist. The above grounded literature papers represent verified, peer-reviewed facts extracted from academic publications.
- Rely strictly on the grounded methodologies, empirical numbers, and research gaps listed above.
- Do not hallucinate external benchmarks when contradicting the extracted papers.
- Provide a rigorous, mathematically formal synthesis addressing the user's research inquiry.
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(contextText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([contextText], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `LitBuddy_Context_${(topic || 'Research').replace(/[^a-z0-9]/gi, '_')}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-150">
      <div className="w-full max-w-2xl rounded-2xl antigravity-glass p-6 text-zinc-200 border border-white/10 shadow-2xl relative flex flex-col max-h-[85vh]">
        <div className="flex items-center justify-between pb-3 border-b border-zinc-800 shrink-0">
          <div className="flex items-center gap-2">
            <Share2 className="w-4 h-4 text-zinc-300" />
            <div>
              <h3 className="font-semibold text-sm text-zinc-100">Export Context for External AI</h3>
              <p className="text-[11px] text-zinc-400">Shift seamlessly to ChatGPT, Claude, or Gemini with full literature memory</p>
            </div>
          </div>
          <button type="button" onClick={onClose} className="text-zinc-400 hover:text-white p-1">
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="mt-4 flex-1 overflow-y-auto rounded-xl bg-zinc-950/80 border border-zinc-800/80 p-3.5 font-mono text-xs text-zinc-300 leading-relaxed whitespace-pre-wrap select-all">
          {contextText}
        </div>

        <div className="pt-4 border-t border-zinc-800 flex items-center justify-between shrink-0">
          <span className="text-[11px] text-zinc-500 font-sans">
            Includes {synthesizedPapers.length} papers, DOIs, methodologies &amp; gaps
          </span>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleDownload}
              className="px-3 py-1.5 bg-zinc-900 hover:bg-zinc-800 border border-zinc-700 text-zinc-200 rounded-lg font-medium text-xs flex items-center gap-1.5 transition"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download .md</span>
            </button>

            <button
              type="button"
              onClick={handleCopy}
              className="px-4 py-1.5 bg-zinc-100 hover:bg-white text-zinc-950 rounded-lg font-semibold text-xs flex items-center gap-1.5 transition shadow-md"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied to Clipboard!' : 'Copy AI Prompt'}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
